[workspace]
authors = ["bingli <bing.li@ess.eu>"]
channels = ["conda-forge"]
name = "mdnorm"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.6,<3.15"
scipp = ">=25.12.0,<26"
scippneutron = ">=26.7.0,<27"
mcstas = ">=3.7.17,<4"
mcstasscript = ">=0.0.90"
mcstastox = ">=0.0.12"
